
import streamlit as st
from pages import *

def main():

    st.write("# TxGraffiti")

    st.markdown(
        """
        TxGraffiti is an artificial intelligence designed to generate potential research conjectures in graph theory.
        Developed using Python, and inspired Fajtlowicz's GRAFFITI and DeLaVina's Graffiti.pc,
        TxGraffiti leverages machine learning and fine-tuned heuristics to identify significant relationships
        within mathematical data. By systematically calculating numerical properties and testing for potential inequalities,
        TxGraffiti highlights the most promising conjectures for further exploration.

        ## Terms of Usage
        I do not ask to be on any papers that result from the use of TxGraffiti, but I would appreciate a mention in the acknowledgements
        and a citation given to the TxGraffiti website. I am always happy to hear about the results of using TxGraffiti, or to work collaboratively
        with you, so please feel free to contact me at rrd6@rice.edu if you wish to discuss anything further. Also, in the future I will be
        adding a feature to the website where you can submit your counter-examples to the conjectures generated by TxGraffiti, as
        well as submit results of conjectures that have been proven. This will help to improve the conjectures made by TxGraffiti further.

        ### Contact
        - TxGraffiti Creator: Randy R. Davila, PhD

        - Email: rrd6@rice.edu.

        """
    )



if __name__ == "__main__":
    main()
